%% Load data for calculating average residence time & average relative velocity
% Trajectories (generated by loadAllTrajectories.m) contains the following info:
%   (:,1) x
%   (:,2) y
%   (:,3) z
%   (:,4) residence time
%   ... (not relevant for calculating residence time and relative velocity)
%   (:,12) particle u_x
%   (:,13) particle u_y
%   (:,14) particle u_z
%   (:,15) gas u_x
%   (:,16) gas u_y
%   (:,17) gas u_z
%   (:,18) time step (cumulative sum of time step is residence time)
%% Load data for all particle trajectories, generally should have been executed already
% loadAllTrajectories;
%% Sort trajectories according to injection diameters
numStream = 25;
[dInjection, traj_dInjection] = sortDiamTraj(numStream, traj);
%% Calculate average residence time and relative velocity in region near outlets
hGasOutHigh = 0.125; % highest height of gas outlet pipe
hGasOutLow = 0.027; % lowest height of gas outlet pipe
% Calculate average residence time and relative velocity in region near gas outlet
[tauAvgGOut, tauGOut, tauArrayGOut, relVelAvgGOut, relVelArrayGOut] = ...
    calcAvgHeight(52e-6, 150e3, dInjection, traj_dInjection, hGasOutLow, hGasOutHigh,1);
% Calculate average residence time and relative velocity in region near particle outlet
[tauAvgPOut, tauPOut, tauArrayPOut, relVelAvgPOut, relVelArrayPOut] = ...
    calcAvgHeight(52e-6, 150e3, dInjection, traj_dInjection, 0, hGasOutLow,1);
% Remark:
%   If the values of residence time and relative velocity of a trajectory are zero, it means this trajectory didn't go into the region
%   Especially in case of small diameters like 1 micron, all particles go
%   through gas outlet and the results in particle outlet region are all
%   NaN, because all arrays are empty
%% Plot average residence time and relative velocity in region near outlets for all diameters
% outletsTau is obtained from 0-experimentData.xslx, sheet "avg", contains
% the mass-flow averaged values:
%   (:,1) injection diameter in meter
%   (:,2) mass-flow averaged residence time at gas outlet
%   (:,3) standard deviation of residence time at gas outlet
%   (:,4) mass-flow averaged average relative velocity at gas outlet
%   (:,5) standard deviation of average relative velocity at gas outlet
%   (:,6) mass-flow averaged residence time at particle outlet
%   (:,7) standard deviation of residence time at particle outlet
%   (:,8) mass-flow averaged average relative velocity at particle outlet
%   (:,9) standard deviation of average relative velocity at particle outlet
% average residence time
figure
errorbar(outletsTau(:,1), outletsTau(:,2), outletsTau(:,3),'-o')
hold on
errorbar(outletsTau(:,1), outletsTau(:,6), outletsTau(:,7),'-o')
grid on
legend('Gas outlet region','Particle outlet region','Interpreter','latex','Location','best');
xlabel('Injection diameter [m]','Interpreter','latex');
ylabel('Average residence time [s]','Interpreter','latex');
ylim([0 0.8]);

% average relative velocity
figure
errorbar(outletsTau(:,1), outletsTau(:,4), outletsTau(:,5),'-o')
hold on
errorbar(outletsTau(:,1), outletsTau(:,8), outletsTau(:,9),'-o')
grid on
legend('Gas outlet region','Particle outlet region','Interpreter','latex','Location','best');
xlabel('Injection diameter [m]','Interpreter','latex');
ylabel('Average relative velocity [m/s]','Interpreter','latex');
% ylim([0 0.8]);
%% Calculate average residence time and relative velocity in bulk region
% for each injection diameter on each height interval
bulk_heights = [0.125 0.13:0.05:1.5 1.52]';
bulk_tauAvg = zeros(size(bulk_heights)-1);
bulk_relVelAvg = zeros(size(bulk_heights)-1);
bulk_dIdx = 1;
for zj = 1:size(dInjection,1) % loop for each injection diameter
    for zi = 1:size(bulk_heights,1)-1 % in each diameter, calculate tau and relVel for each height compartment
        [bulk_tauAvg(zi,bulk_dIdx), ~, ~, ~, ~] = ...
            calcAvgHeight(dInjection(zj), 150e3, dInjection, traj_dInjection, ...
            bulk_heights(zi), bulk_heights(zi+1), 0);
        [~, ~, ~, bulk_relVelAvg(zi,bulk_dIdx), ~] = ...
            calcAvgHeight(dInjection(zj), 150e3, dInjection, traj_dInjection, ...
            bulk_heights(zi), bulk_heights(zi+1), 0);
    end
    bulk_dIdx = bulk_dIdx +1;
end
bulk_tauAvg(isnan(bulk_tauAvg)) = 0;
bulk_relVelAvg(isnan(bulk_relVelAvg)) = 0;
[bulk_d, bulk_h] = meshgrid(dInjection, (bulk_heights(1:end-1) + bulk_heights(2:end))/2); %(bulk_heights(1:end-1) + bulk_heights(2:end))/2

%% for each height interval, average of all injection diameters
z_avgTauAll = zeros(size(bulk_heights,1)-1,1);
z_avgRelVelAll = zeros(size(bulk_heights,1)-1,1);
for zk = 1:size(bulk_heights,1)-1
    z_hLow = bulk_heights(zk,1);
    z_hHigh = bulk_heights(zk+1,1);
    [z_avgTauAll(zk), ~, ~] = calcAvgHeightAllDiam(150e3, traj, z_hLow, z_hHigh);
    [~, z_avgRelVelAll(zk), ~] = calcAvgHeightAllDiam(150e3, traj, z_hLow, z_hHigh);
end
%%
figure
set(gca,'Yscale','log')
plot((bulk_heights(1:end-1) + bulk_heights(2:end))/2, z_avgTauAll)

figure
plot((bulk_heights(1:end-1) + bulk_heights(2:end))/2, z_avgRelVelAll)
%% Plot average residence time and relative velocity
% residence time
figure
set(gcf,'renderer','Painters')
surf(bulk_d, bulk_h, bulk_tauAvg)
xlabel('Injection diameter [m]', 'Interpreter','latex');
ylabel('Height [m]', 'Interpreter','latex');
zlabel('Average residence time [s]', 'Interpreter','latex');
ylim([0.125 1.52])
zlim([0 5])
yticks([0.125 0.4 0.6 0.8 1 1.2 1.385 1.52]);
ytickangle(45)
colorbar;
hold on
pltAvgTau = plot3(zeros(size(z_avgTauAll)), (bulk_heights(1:end-1) + bulk_heights(2:end))/2, z_avgTauAll, ...
    'Color','red','LineWidth',3);
legend(pltAvgTau, 'Average weighed by mass flow of injection diameters','Interpreter','latex')

% relative velocity
figure
set(gcf,'renderer','Painters')
surf(bulk_d, bulk_h, bulk_relVelAvg)
xlabel('Injection diameter [m]', 'Interpreter','latex');
ylabel('Height [m]', 'Interpreter','latex');
zlabel('Average relative velocity [m/s]', 'Interpreter','latex');
ylim([0.125 1.52])
yticks([0.125 0.4 0.6 0.8 1 1.2 1.385 1.52]);
ytickangle(45)
colorbar
hold on
pltAvgRelVel = plot3(zeros(size(z_avgRelVelAll)), (bulk_heights(1:end-1) + bulk_heights(2:end))/2, z_avgRelVelAll, ...
    'Color','red','LineWidth',3);
legend(pltAvgRelVel, 'Average weighed by mass flow of injection diameters','Interpreter','latex')
%% Plot average residence time and relative velocity for a given injection diameter
[ztauAvg, ztauDev, ztauArray, zrelVelAvg, zrelVelArray] = ...
    calcAvgHeight(60e-6, 150e3, dInjection, traj_dInjection, 1.2, 1.5, 1);
%% Calculate average residence time and relative velocity in bulk region for all diameters
[avgTauAll, avgRelVelAll, avgArray] = calcAvgHeightAllDiam(150e3, traj, 1.3, 1.4);