% Script for importing raw data generated by Fluent
% First to use for prost-processing
% Import data using "uiimport", this must be done manually one after another

% by Xiye Zhou, Oct. 2021
%% import data 01 - 22 microns including gas x velocity
uiimport('simulationData/150ksteps-experimentBC-res0.99/allData/d01-22velX.txt');
%% import data 01 - 22 microns including gas y velocity
uiimport('simulationData/150ksteps-experimentBC-res0.99/allData/d01-22velY.txt');
%% import data 01 - 22 microns including gas z velocity
uiimport('simulationData/150ksteps-experimentBC-res0.99/allData/d01-22velZ.txt');
%% Organize data according to loadAllTrajectories.m
d0122velX = movevars(d0122velX, 'tau', 'Before', 'dFluent');
d0122velX(:,17) = d0122velY;
d0122velX.Properties.VariableNames{17} = 'gUy';
d0122velX(:,18) = d0122velZ;
d0122velX.Properties.VariableNames{18} = 'gUz';
d0122velX = movevars(d0122velX, 'timeStep', 'After', 'gUz');
writetable(d0122velX,'simulationData/150ksteps-experimentBC-res0.99/d01-22loaded.txt');
%%
%%%%%%%%%%
%  Take a break   %
%%%%%%%%%%
%% import data 27 - 42 microns including gas x velocity
uiimport('simulationData/150ksteps-experimentBC-res0.99/allData/d27-42velX.txt');
%% import data 27 - 42 microns including gas y velocity
uiimport('simulationData/150ksteps-experimentBC-res0.99/allData/d27-42velY.txt');
%% import data 27 - 42 microns including gas z velocity
uiimport('simulationData/150ksteps-experimentBC-res0.99/allData/d27-42velZ.txt');
%% Organize data according to loadAllTrajectories.m
d2742velX = movevars(d2742velX, 'tau', 'Before', 'dFluent');
d2742velX(:,17) = d2742velY;
d2742velX.Properties.VariableNames{17} = 'gUy';
d2742velX(:,18) = d2742velZ;
d2742velX.Properties.VariableNames{18} = 'gUz';
d2742velX = movevars(d2742velX, 'timeStep', 'After', 'gUz');
writetable(d2742velX,'simulationData/150ksteps-experimentBC-res0.99/d27-42loaded.txt');
%%
%%%%%%%%%%
%  Take a break   %
%%%%%%%%%%
%% import data 47 - 60 microns including gas x velocity
uiimport('simulationData/150ksteps-experimentBC-res0.99/allData/d47-60velX.txt');
%% import data 47 - 60 microns including gas y velocity
uiimport('simulationData/150ksteps-experimentBC-res0.99/allData/d47-60velY.txt');
%% import data 47 - 60 microns including gas z velocity
uiimport('simulationData/150ksteps-experimentBC-res0.99/allData/d47-60velZ.txt');
%% Organize data according to loadAllTrajectories.m
d4760velX = movevars(d4760velX, 'tau', 'Before', 'dFluent');
d4760velX(:,17) = d4760velY;
d4760velX.Properties.VariableNames{17} = 'gUy';
d4760velX(:,18) = d4760velZ;
d4760velX.Properties.VariableNames{18} = 'gUz';
d4760velX = movevars(d4760velX, 'timeStep', 'After', 'gUz');
writetable(d4760velX,'simulationData/150ksteps-experimentBC-res0.99/d47-60loaded.txt');