function [] = plotTraj(dStream, traj, plotIdxTraj)
%Plot trajectories of given trajectory ID in cell "traj"
% Input:
%   dStream: injection diameter of trajectories with indices in plotIdxTraj
%   traj: cell containing info of all trajectories, generated by loadAllTrajectories.m
%   plotIdxTraj: array containing indices of trajectories in cell "traj"

% by Xiye Zhou, Oct. 2021
%% Plot trajectories colored by injection diameter
figure
% set plot size
pltx0=300;
plty0=300;
pltwidth=500;
pltheight=600;
set(gcf,'position', [pltx0,plty0,pltwidth,pltheight])
set(gcf,'renderer','Painters')
% set plot colormap
colormap parula;
cmap = colormap;
colorCount = 1;
for i = 1:size(plotIdxTraj,1)
    plotColor = cmap(colorCount, :);
    plot3(traj{plotIdxTraj(i),1}(:,1),traj{plotIdxTraj(i),1}(:,3),traj{plotIdxTraj(i),1}(:,2),'Color',plotColor,'LineWidth',1);
    hold on;
    colorCount = colorCount + size(cmap,1) / size(plotIdxTraj,1);
end
grid on
xlim([-0.397 0.397])
ylim([-0.397 0.397])
zlim([0 1.52])
lgdStream = dStream * 1e6; % array for injection diameters of corresponding trajectory ID
lgdDiam = char(ones(size(lgdStream)) * '$$d_{inj}$$ = ');
lgdNum = num2str(lgdStream, '%d');
lgdUnit = char(ones(size(lgdStream)) * ' $$\mu$$m');
legend([lgdDiam lgdNum lgdUnit],'Interpreter','latex','Location','best');
xlabel('$x$ [m]', 'Interpreter','latex');
ylabel('$z$ [m]', 'Interpreter','latex');
zlabel('$y$ [m]', 'Interpreter','latex');
%% plot trajectories colored by residence time
figure
set(gcf,'position', [pltx0,plty0,pltwidth,pltheight])
set(gcf,'renderer','Painters')
for i = 1:size(plotIdxTraj,1)
    scatter3(traj{plotIdxTraj(i),1}(:,1),traj{plotIdxTraj(i),1}(:,3),traj{plotIdxTraj(i),1}(:,2), 0.5, traj{plotIdxTraj(i),1}(:,4));
    hold on;
end
grid on
xlim([-0.397 0.397])
ylim([-0.397 0.397])
zlim([0 1.52])
xlabel('$x$ [m]', 'Interpreter','latex');
ylabel('$z$ [m]', 'Interpreter','latex');
zlabel('$y$ [m]', 'Interpreter','latex');
colormap winter;
tauBar = colorbar;
tauBar.Label.String = 'Residence time [s]';
tauBar.Label.Interpreter = 'latex';
end